// <auto-generated />
using System;
using Ap1_SegundoP_ErissonSilverio.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ap1_SegundoP_ErissonSilverio.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200317001015_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("Ap1_SegundoP_ErissonSilverio.Entidades.LlamadaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LlamadaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LlamdaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Problema")
                        .HasColumnType("TEXT");

                    b.Property<string>("Solucion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LlamadaId");

                    b.ToTable("LlamadaDetalle");
                });

            modelBuilder.Entity("Ap1_SegundoP_ErissonSilverio.Entidades.Llamadas", b =>
                {
                    b.Property<int>("LlamadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Problema")
                        .HasColumnType("TEXT");

                    b.Property<string>("Solucion")
                        .HasColumnType("TEXT");

                    b.HasKey("LlamadaId");

                    b.ToTable("llamadas");
                });

            modelBuilder.Entity("Ap1_SegundoP_ErissonSilverio.Entidades.LlamadaDetalle", b =>
                {
                    b.HasOne("Ap1_SegundoP_ErissonSilverio.Entidades.Llamadas", null)
                        .WithMany("LlamadasDetalles")
                        .HasForeignKey("LlamadaId");
                });
#pragma warning restore 612, 618
        }
    }
}
